// <auto-generated />
using System;
using ArtGallery.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtGallery.Migrations
{
    [DbContext(typeof(ArtGalleryContext))]
    [Migration("20250430092249_messagesticker")]
    partial class messagesticker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtGallery.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_binh_luan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<bool>("DaChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_chinh_sua");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<DateTime?>("NgayBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_binh_luan")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating");

                    b.Property<string>("Sticker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sticker");

                    b.HasKey("MaBinhLuan")
                        .HasName("PK__binh_lua__300DD2D8D7F67231");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTranh");

                    b.ToTable("binh_luan", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.DoanhThu", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int?>("SoTranhBanDuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_tranh_ban_duoc");

                    b.Property<decimal?>("TongDoanhThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_doanh_thu");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__doanh_th__19C32CF7AA9DECC6");

                    b.ToTable("doanh_thu", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.GiaoDich", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_giao_dich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<bool?>("IsHiddenByBuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden_by_buyer");

                    b.Property<bool?>("IsHiddenBySeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden_by_seller");

                    b.Property<string>("MaNguoiMua")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_mua");

                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<DateTime?>("NgayMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_mua")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaGiaoDich")
                        .HasName("PK__giao_dic__FB80ED3254B2912A");

                    b.HasIndex("MaNguoiMua");

                    b.HasIndex("MaTranh");

                    b.ToTable("giao_dich", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.LuotThich", b =>
                {
                    b.Property<int>("MaLuotThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_luot_thich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuotThich"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<DateTime?>("NgayThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_thich")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLuotThich")
                        .HasName("PK__luot_thi__64AF50517DA222E2");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex(new[] { "MaTranh", "MaNguoiDung" }, "unique_like")
                        .IsUnique();

                    b.ToTable("luot_thich", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.LuuTranh", b =>
                {
                    b.Property<int>("MaLuuTranh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_luu_tranh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuuTranh"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<DateTime?>("NgayLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_luu")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLuuTranh")
                        .HasName("PK__luu_tran__0893EFAE9404701B");

                    b.HasIndex("MaTranh");

                    b.HasIndex(new[] { "MaNguoiDung", "MaTranh" }, "unique_bookmark")
                        .IsUnique();

                    b.ToTable("luu_tranh", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Medium", b =>
                {
                    b.Property<int>("MaMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_media");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMedia"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan");

                    b.Property<string>("LoaiMedia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_media");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.HasKey("MaMedia")
                        .HasName("PK__media__6CED7F1DFD307904");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaiHat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DangKyNgheSi")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HienThiDiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HienThiGioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HienThiNamSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HienThiNgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.NoiBat", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaNguoiDung", "MaTranh")
                        .HasName("PK__noi_bat__CFF08069508BECFF");

                    b.HasIndex("MaTranh");

                    b.ToTable("noi_bat", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.PhanHoiBinhLuan", b =>
                {
                    b.Property<int>("MaPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phan_hoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanHoi"));

                    b.Property<bool>("DaChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_chinh_sua");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<int>("MaBinhLuan")
                        .HasColumnType("int")
                        .HasColumnName("ma_binh_luan");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_phan_hoi")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("Sticker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sticker");

                    b.HasKey("MaPhanHoi")
                        .HasName("PK__phan_hoi_binh_luan__ID");

                    b.HasIndex("MaBinhLuan");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("phan_hoi_binh_luan", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_the_loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_the_loai");

                    b.HasKey("MaTheLoai")
                        .HasName("PK__the_loai__489AA0F38C7B2D0E");

                    b.HasIndex(new[] { "TenTheLoai" }, "UQ__the_loai__87296EA3BFC72A9B")
                        .IsUnique();

                    b.ToTable("the_loai", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.TheTag", b =>
                {
                    b.Property<int>("MaTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_tag");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTag"));

                    b.Property<string>("TenTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_tag");

                    b.HasKey("MaTag")
                        .HasName("PK__the_tag__099A6217E57B8670");

                    b.HasIndex(new[] { "TenTag" }, "UQ__the_tag__56DB79DEC5AA1248")
                        .IsUnique();

                    b.ToTable("the_tag", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.TheoDoi", b =>
                {
                    b.Property<string>("MaNguoiTheoDoi")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_theo_doi");

                    b.Property<string>("MaNguoiDuocTheoDoi")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_duoc_theo_doi");

                    b.Property<DateTime?>("NgayTheoDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_theo_doi")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaNguoiTheoDoi", "MaNguoiDuocTheoDoi")
                        .HasName("PK__theo_doi__E8A6156EE67C0BC9");

                    b.HasIndex("MaNguoiDuocTheoDoi");

                    b.ToTable("theo_doi", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thong_bao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool?>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("da_doc")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("DuongDanAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_thong_bao");

                    b.Property<string>("MaNguoiGui")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_gui");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_nhan");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_tin_nhan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_doc");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("MaNguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_gui");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_nhan");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("Sticker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sticker");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaTinNhan")
                        .HasName("PK__tin_nhan__ID");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("tin_nhan", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Tranh", b =>
                {
                    b.Property<int>("MaTranh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTranh"));

                    b.Property<int>("DaBan")
                        .HasColumnType("int")
                        .HasColumnName("da_ban");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dang")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieu_de");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang bán")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaTranh")
                        .HasName("PK__tranh__633AC9ECC367B622");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("tranh", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("TranhTheLoai", b =>
                {
                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_the_loai");

                    b.HasKey("MaTranh", "MaTheLoai")
                        .HasName("PK__tranh_th__47B363E3D8A01C76");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("tranh_the_loai", (string)null);
                });

            modelBuilder.Entity("TranhTheTag", b =>
                {
                    b.Property<int>("MaTranh")
                        .HasColumnType("int")
                        .HasColumnName("ma_tranh");

                    b.Property<int>("MaTag")
                        .HasColumnType("int")
                        .HasColumnName("ma_tag");

                    b.HasKey("MaTranh", "MaTag")
                        .HasName("PK__tranh_th__03A36FCDE94B1BA4");

                    b.HasIndex("MaTag");

                    b.ToTable("tranh_the_tag", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.BinhLuan", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__binh_luan__ma_ng__0E591826");

                    b.HasOne("ArtGallery.Models.Tranh", "MaTranhNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__binh_luan__ma_tr__0D64F3ED");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaTranhNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.DoanhThu", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithOne("DoanhThu")
                        .HasForeignKey("ArtGallery.Models.DoanhThu", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__doanh_thu__ma_ng__290D0E62");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.GiaoDich", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiMuaNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaNguoiMua")
                        .IsRequired()
                        .HasConstraintName("FK__giao_dich__ma_ng__2354350C");

                    b.HasOne("ArtGallery.Models.Tranh", "MaTranhNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaTranh")
                        .IsRequired()
                        .HasConstraintName("FK__giao_dich__ma_tr__24485945");

                    b.Navigation("MaNguoiMuaNavigation");

                    b.Navigation("MaTranhNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.LuotThich", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LuotThiches")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__luot_thic__ma_ng__1411F17C");

                    b.HasOne("ArtGallery.Models.Tranh", "MaTranhNavigation")
                        .WithMany("LuotThiches")
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__luot_thic__ma_tr__131DCD43");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaTranhNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.LuuTranh", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LuuTranhs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__luu_tranh__ma_ng__1D9B5BB6");

                    b.HasOne("ArtGallery.Models.Tranh", "MaTranhNavigation")
                        .WithMany("LuuTranhs")
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__luu_tranh__ma_tr__1E8F7FEF");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaTranhNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.Medium", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("Media")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__media__ma_nguoi___2CDD9F46");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.NoiBat", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NoiBats")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__noi_bat__ma_nguo__31A25463");

                    b.HasOne("ArtGallery.Models.Tranh", "MaTranhNavigation")
                        .WithMany("NoiBats")
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__noi_bat__ma_tran__3296789C");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaTranhNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.PhanHoiBinhLuan", b =>
                {
                    b.HasOne("ArtGallery.Models.BinhLuan", "MaBinhLuanNavigation")
                        .WithMany()
                        .HasForeignKey("MaBinhLuan")
                        .IsRequired()
                        .HasConstraintName("FK__phan_hoi__ma_binh_luan");

                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__phan_hoi__ma_nguoi_dung");

                    b.Navigation("MaBinhLuanNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.TheoDoi", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDuocTheoDoiNavigation")
                        .WithMany("TheoDoiMaNguoiDuocTheoDoiNavigations")
                        .HasForeignKey("MaNguoiDuocTheoDoi")
                        .IsRequired()
                        .HasConstraintName("FK__theo_doi__ma_ngu__18D6A699");

                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiTheoDoiNavigation")
                        .WithMany("TheoDoiMaNguoiTheoDoiNavigations")
                        .HasForeignKey("MaNguoiTheoDoi")
                        .IsRequired()
                        .HasConstraintName("FK__theo_doi__ma_ngu__17E28260");

                    b.Navigation("MaNguoiDuocTheoDoiNavigation");

                    b.Navigation("MaNguoiTheoDoiNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.ThongBao", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiGuiNavigation")
                        .WithMany()
                        .HasForeignKey("MaNguoiGui")
                        .HasConstraintName("FK_ThongBao_AspNetUsers_NguoiGui");

                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiNhanNavigation")
                        .WithMany()
                        .HasForeignKey("MaNguoiNhan")
                        .IsRequired()
                        .HasConstraintName("FK_ThongBao_AspNetUsers_NguoiNhan");

                    b.Navigation("MaNguoiGuiNavigation");

                    b.Navigation("MaNguoiNhanNavigation");
                });

            modelBuilder.Entity("ArtGallery.Models.TinNhan", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("MaNguoiGui")
                        .IsRequired()
                        .HasConstraintName("FK__tin_nhan__ma_nguoi_gui");

                    b.HasOne("ArtGallery.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaNguoiNhan")
                        .IsRequired()
                        .HasConstraintName("FK__tin_nhan__ma_nguoi_nhan");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("ArtGallery.Models.Tranh", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("Tranhs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tranh__ma_nguoi___7C3A67EB");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtGallery.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ArtGallery.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TranhTheLoai", b =>
                {
                    b.HasOne("ArtGallery.Models.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tranh_the__ma_th__02E7657A");

                    b.HasOne("ArtGallery.Models.Tranh", null)
                        .WithMany()
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tranh_the__ma_tr__01F34141");
                });

            modelBuilder.Entity("TranhTheTag", b =>
                {
                    b.HasOne("ArtGallery.Models.TheTag", null)
                        .WithMany()
                        .HasForeignKey("MaTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tranh_the__ma_ta__09946309");

                    b.HasOne("ArtGallery.Models.Tranh", null)
                        .WithMany()
                        .HasForeignKey("MaTranh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__tranh_the__ma_tr__08A03ED0");
                });

            modelBuilder.Entity("ArtGallery.Models.NguoiDung", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DoanhThu");

                    b.Navigation("GiaoDiches");

                    b.Navigation("LuotThiches");

                    b.Navigation("LuuTranhs");

                    b.Navigation("Media");

                    b.Navigation("NoiBats");

                    b.Navigation("TheoDoiMaNguoiDuocTheoDoiNavigations");

                    b.Navigation("TheoDoiMaNguoiTheoDoiNavigations");

                    b.Navigation("Tranhs");
                });

            modelBuilder.Entity("ArtGallery.Models.Tranh", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("GiaoDiches");

                    b.Navigation("LuotThiches");

                    b.Navigation("LuuTranhs");

                    b.Navigation("NoiBats");
                });
#pragma warning restore 612, 618
        }
    }
}
